### ISSUE TITLE
PCB review request 2nd iteration

### ISSUE THREAD

**Issue by ashishvankara** [ashishvankara/AshishVankaraLED#12]
Hopefully this is my finalized PCB!

**Comment by sphaerobolus** [comment]
Looks good to go. 

If (and only if) you want to pick nits, you could improve the routing of N$6 and N$3. They're both convoluted and make unnecessary twists and turns. This is a style criticism, not an indictment against functionality.

**Comment by sphaerobolus** [comment]
Looks good. I don't think we have the LED you placed, but I think we can make something fit.
