### ISSUE TITLE
Milestone 04 Review

### ISSUE THREAD

**Issue by ashishvankara** [ashishvankara/AshishVankaraLED#9]
I designed a one-sided board with through hole components

**Comment by sphaerobolus** [comment]
Your .brd is not up to date with the .pdf image of same. 

While not required, I think you could size your board a lot smaller. 

Good idea to keep the crystal and its associated capacitors physically close to their ATMEGA pins to reduce parasitic reactance. 

See if you can reduce that "island" in your copper pour, near the crystal.
